#!/usr/bin/env python3
"""port.py: one-time port of the WordPress pages into static pages with the same URLs.

Reads _port/wp-pages/<slug>.rendered.html (the live page as served), keeps the article
content (headings, paragraphs, lists, tables, links, images), drops the Elementor scaffolding
and all scripts/styles, and writes <slug>/index.html through templates/page.html.
Run once:  python3 tools/port.py     Re-run safely; it overwrites the ported pages only.
"""
import os, re, html, json, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "_port", "wp-pages")
SITE = json.load(open(os.path.join(ROOT, "site.json"), encoding="utf-8"))
TPL = open(os.path.join(ROOT, "templates", "page.html"), encoding="utf-8").read()
KEEP = {"h1", "h2", "h3", "h4", "p", "ul", "ol", "li", "table", "thead", "tbody", "tr", "th", "td", "a", "strong", "em", "b", "i", "img", "br", "blockquote", "code", "pre"}
SKIP = {"home-3"}  # the front page is generated by build.py

def clean(fragment):
    fragment = re.sub(r"<(script|style|noscript|svg|form|button|iframe)[^>]*>.*?</\1>", "", fragment, flags=re.S | re.I)
    def tag(m):
        closing, name, attrs = m.group(1), m.group(2).lower(), m.group(3) or ""
        if name not in KEEP: return ""
        if closing: return f"</{name}>"
        keep = []
        if name == "a":
            href = re.search(r'href\s*=\s*"([^"]*)"', attrs)
            if href:
                h = href.group(1).replace("https://stratos.games/", "../").replace("http://stratos.games/", "../")
                keep.append(f'href="{html.escape(h, quote=True)}"')
                if h.startswith("http"): keep.append('target="_blank" rel="noopener"')
        if name == "img":
            src = re.search(r'src\s*=\s*"([^"]*)"', attrs); alt = re.search(r'alt\s*=\s*"([^"]*)"', attrs)
            if not src: return ""
            keep.append(f'src="{html.escape(src.group(1), quote=True)}"'); keep.append(f'alt="{html.escape(alt.group(1) if alt else "", quote=True)}"'); keep.append('loading="lazy"')
        return f"<{name}{(' ' + ' '.join(keep)) if keep else ''}>"
    out = re.sub(r"<(/?)([a-zA-Z0-9]+)([^>]*)>", tag, fragment)
    out = re.sub(r"\n\s*\n+", "\n", out)
    out = re.sub(r"<p>\s*</p>", "", out)
    return out.strip()

def port(slug):
    raw = open(os.path.join(SRC, f"{slug}.rendered.html"), encoding="utf-8", errors="replace").read()
    body = re.search(r"<main.*?</main>", raw, flags=re.S | re.I) or re.search(r"<body.*?</body>", raw, flags=re.S | re.I)
    frag = body.group(0) if body else raw
    # drop the header/footer if they sit inside main
    frag = re.sub(r"<header.*?</header>", "", frag, flags=re.S | re.I); frag = re.sub(r"<footer.*?</footer>", "", frag, flags=re.S | re.I)
    content = clean(frag)
    title = re.search(r"<h1[^>]*>(.*?)</h1>", content, flags=re.S)
    title = html.unescape(re.sub(r"<[^>]+>", "", title.group(1))).strip() if title else slug.replace("-", " ").title()
    desc = re.search(r"<p[^>]*>(.*?)</p>", content, flags=re.S)
    desc = html.unescape(re.sub(r"<[^>]+>", "", desc.group(1))).strip()[:155] if desc else SITE["tagline"]
    page = (TPL.replace("{{TITLE}}", html.escape(title)).replace("{{DESCRIPTION}}", html.escape(desc, quote=True))
               .replace("{{SLUG}}", slug).replace("{{SITE_URL}}", SITE["url"]).replace("{{CONTENT}}", content)
               .replace("{{YEAR}}", str(datetime.date.today().year)))
    os.makedirs(os.path.join(ROOT, slug), exist_ok=True)
    open(os.path.join(ROOT, slug, "index.html"), "w", encoding="utf-8").write(page)
    words = len(re.sub(r"<[^>]+>", " ", content).split())
    return title, words

if __name__ == "__main__":
    for f in sorted(os.listdir(SRC)):
        if not f.endswith(".rendered.html"): continue
        slug = f[: -len(".rendered.html")]
        if slug in SKIP: continue
        t, w = port(slug); print(f"  {slug}/index.html  <- {t!r} ({w} words)")
